In [1]:
import sys, os
sys.path.append(os.path.join(os.getcwd(), "../../"))

In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import agreement_utils as calc
from itertools import combinations
from utils.plots import set_plot_params
from readers.memo_ga import MEMOGroupAff

In [6]:
def load_labels():
    memodb = MEMOGroupAff()
    labels_df = pd.read_csv(memodb.joint_labels_df_path)
    return labels_df, memodb.groups, memodb.sessions, memodb.emo_dims, memodb.annotators, memodb

In [14]:
labels_df, groups, sessions, emo_dims, annotators, memodb = load_labels()

In [15]:
labels_df["ArousalAvg"] = 0.0
labels_df["ValenceAvg"] = 0.0

In [16]:
labels_df.head()

Unnamed: 0 interactionID  groupID  sessionID  onsetTime  offsetTime  \
0           0           4_1        4          1          0          15   
1           1           4_1        4          1         15          30   
2           2           4_1        4          1         30          45   
3           3           4_1        4          1         45          60   
4           4           4_1        4          1         60          75   

   Arousal_004  Valence_004  Arousal_001  Valence_001  ...  Arousal_005  \
0          2.0          4.0          3.0          5.0  ...          NaN   
1          4.0          5.0          5.0          6.0  ...          NaN   
2          3.0          5.0          4.0          6.0  ...          NaN   
3          3.0          5.0          5.0          5.0  ...          NaN   
4          3.0          5.0          4.0          6.0  ...          NaN   

   Valence_005  Arousal_006  Valence_006  Arousal_007  Valence_007  \
0          NaN          3.0          5.0          NaN          NaN   
1          NaN          6.0          6.0          NaN          NaN   
2          NaN          5.0          6.0          NaN          NaN   
3          NaN          6.0          6.0          NaN          NaN   
4          NaN          5.0          6.0          NaN          NaN   

   Arousal_008  Valence_008  ArousalAvg  ValenceAvg  
0          1.0          4.0         0.0         0.0  
1          4.0          6.0         0.0         0.0  
2          4.0          5.0         0.0         0.0  
3          3.0          5.0         0.0         0.0  
4          4.0          5.0         0.0         0.0  

[5 rows x 24 columns]

In [39]:
def get_annots_from_row(row, cols, emo_dim):
    req_cols = list(filter(lambda k: emo_dim+"_00" in k, cols)) 
    print(req_cols)
    annots = row[req_cols].dropna().values
    print(annots)
    return annots

for index, row in labels_df.iterrows():
    arous_avg = np.mean(get_annots_from_row(row, labels_df.columns, "Arousal"))
    valen_avg = np.mean(get_annots_from_row(row, labels_df.columns, "Valence"))
    
    labels_df.loc[index, "ArousalAvg"] = arous_avg
    labels_df.loc[index, "ValenceAvg"] = valen_avg


['Arousal_004', 'Arousal_001', 'Arousal_002', 'Arousal_003', 'Arousal_005', 'Arousal_006', 'Arousal_007', 'Arousal_008']
[2.0 3.0 4.0 3.0 1.0]
['Valence_004', 'Valence_001', 'Valence_002', 'Valence_003', 'Valence_005', 'Valence_006', 'Valence_007', 'Valence_008']
[4.0 5.0 5.0 5.0 4.0]
['Arousal_004', 'Arousal_001', 'Arousal_002', 'Arousal_003', 'Arousal_005', 'Arousal_006', 'Arousal_007', 'Arousal_008']
[4.0 5.0 6.0 6.0 4.0]
['Valence_004', 'Valence_001', 'Valence_002', 'Valence_003', 'Valence_005', 'Valence_006', 'Valence_007', 'Valence_008']
[5.0 6.0 6.0 6.0 6.0]
['Arousal_004', 'Arousal_001', 'Arousal_002', 'Arousal_003', 'Arousal_005', 'Arousal_006', 'Arousal_007', 'Arousal_008']
[3.0 4.0 5.0 5.0 4.0]
['Valence_004', 'Valence_001', 'Valence_002', 'Valence_003', 'Valence_005', 'Valence_006', 'Valence_007', 'Valence_008']
[5.0 6.0 5.0 6.0 5.0]
['Arousal_004', 'Arousal_001', 'Arousal_002', 'Arousal_003', 'Arousal_005', 'Arousal_006', 'Arousal_007', 'Arousal_008']
[3.0 5.0 6.0 6.0 3.0]

In [41]:
print(labels_df["ArousalAvg"])
print(labels_df["ValenceAvg"])

0       2.6
1       5.0
2       4.2
3       4.6
4       4.4
       ... 
5789    6.2
5790    6.2
5791    6.2
5792    6.8
5793    7.6
Name: ArousalAvg, Length: 5794, dtype: float64
0       4.6
1       5.8
2       5.4
3       5.4
4       5.6
       ... 
5789    6.4
5790    6.6
5791    6.8
5792    6.8
5793    7.6
Name: ValenceAvg, Length: 5794, dtype: float64


In [46]:
labels_df.to_csv(memodb.joint_labels_df_path.split(".csv")[0]+"_gt.csv")